### ISSUE TITLE
Importing module "fava_dashboards" failed

### ISSUE THREAD

**Issue by seowalex** [andreasgerstmayr/fava-dashboards#199]
```
Importing module "fava_dashboards" failed.
Error: "cannot import name 'render_template_string' from 'fava.application'
```

Caused by https://github.com/beancount/fava/commit/f207471b7596dd53198f72ff89eb8664ac75216e. It seems that it was imported directly from Flask, so perhaps we could do the same?

The only 2 considerations that come to mind are that Flask is not a direct dependency at the moment, and this is only used in the legacy dashboards.

**Comment by andreasgerstmayr** [comment]
Thanks for reporting this!
